title: Vaneet Saini
logo: /assets/pic.png
#description: text below image
# show_downloads: true
theme: minima

# email: vaneetsaini@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Vaneet Saini's Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  v-saini

plugins:
  # - jekyll-feed
  - jekyll-remote-theme
